version: "3.9"
services:
  mongo:
    image: mongo:7
    ports: ["27017:27017"]
    volumes:
      - mongo-data:/data/db

  chat:
    build: .
    depends_on: [mongo]
    environment:
      PORT: "8080"
      MONGO_URI: "mongodb://mongo:27017"
      MONGO_DB: "chat"
      DJANGO_BASE_URL: "http://192.168.0.101:8000"
    ports: ["8080:8080"]

  # optional: UI ko'rish uchun
  mongo_express:
    image: mongo-express:1.0.2
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
    ports: ["8081:8081"]
    depends_on: [mongo]

volumes:
  mongo-data:
